FROM python:3.11-slim

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir mlflow==2.15.1

WORKDIR /mlflow

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow.db", "--serve-artifacts", "--artifacts-destination", "/mlflow/artifacts"]
